# Generated by Django 2.1.4 on 2018-12-14 11:20

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=ecomapp.models.img_folder),
        ),
    ]
